name: ollama-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pip:
    - langchain>=0.0.350,<0.3.0
    - langchain-community>=0.2.9
    - langchain-core>=0.1.9
    - chromadb==0.4.18
    - sentence-transformers==2.2.2
    - huggingface-hub==0.19.4
    - requests==2.31.0
    - python-dotenv==1.0.0
    - beautifulsoup4==4.12.2
