name: milvus-product-search
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip>=20.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  - pip:
    - pymilvus>=2.3.0
    - sentence-transformers==2.2.2
    - huggingface-hub==0.16.4
    - transformers==4.30.2
    - python-dotenv>=0.19.0
