name: rag-metrics-eval
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10
  
  # Core Data Science
  - numpy
  - pandas
  - scipy
  
  # Machine Learning
  - scikit-learn
  
  # Visualization
  - matplotlib
  - plotly
  
  # RAG and LLM Dependencies
  - pip
  - pip:
    # Use more flexible version specifications
    - langsmith>=0.0.77,<0.2.0
    - langchain-core>=0.1.0
    - langchain-community>=0.0.38
    - langchain>=0.0.350,<0.2.0
    - ragas==0.2.7
    - openai>=1.3.0,<2.0.0
    - datasets>=2.14.0,<3.0.0
    - python-dotenv>=1.0.0
    
  # Jupyter (optional, but recommended)
  - jupyter
  - ipykernel
  
  # Development Tools
  - black
  - flake8
  - mypy

# Post-install scripts
variables:
  PYTHONPATH: ${CONDA_PREFIX}/lib/python3.10/site-packages
